//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
        public string Sender { get; set; }
        public string Requester { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> NotificateDateTime { get; set; }
    }
}
