//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otp
    {
        public int ID { get; set; }
        public string GeneratedOtp { get; set; }
        public System.DateTime GeneratedOn { get; set; }
        public string Email { get; set; }
        public decimal MobileNumber { get; set; }
    }
}
