//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;

    public partial class Party
    {
        public int ID { get; set; }
        public string PartyAlcoholic { get; set; }
        public string PartyVegetarian { get; set; }
        public string PartyAddress { get; set; }
        public string PartyPlace { get; set; }
        public string BuddyGenderPreference { get; set; }
        public int BuddyMinAgePreference { get; set; }
        public int BuddyMaxAgePreference { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public string PartyTime { get; set; }
        public string IsPartyExpenseShared { get; set; }
        public string IsNightAccomodation { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Email { get; set; }
        public decimal PartyLongitude { get; set; }
        public decimal PartyLatitude { get; set; }
        public string PartyDateString
        {
            get { return PartyDate.Value.ToString("dddd, dd MMMM yyyy"); }
        }

    }
}
