//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public int ID { get; set; }
        public string MessageTo { get; set; }
        public string MessageFrom { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string MessageText { get; set; }
    }
}
